apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  backstage.io/kubernetes-namespace: ${{ values.dsp }} 
resources:
- dsp-job-role.yaml
- dsp-job-rb.yaml
- dsp-job-sa.yaml
- initialize-dsp.yaml
- notebook.yaml
- serviceaccount.yaml
- pvc.yaml