apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dsp-job-role.yaml
- dsp-job-rb.yaml
- dsp-job-sa.yaml
#- dsp-clone-job.yaml
- initialize-dsp.yaml
- notebook.yaml
- serviceaccount.yaml
- pvc.yaml