apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ${{ values.name }}
  janus-idp.io/tekton: ${{ values.name }}
  backstage.io/kubernetes-id: ${{ values.name }}
  backstage.io/kubernetes-namespace: ${{ values.namespace }} 
  app.kubernetes.io/part-of: ${{ values.name }}
resources: 
- initialize-namespace.yaml
{%- if values.vllmSelected %}
- pvc.yaml
{%- endif %}
{%- if not values.existingModelServer %}
- deployment-model-server.yaml
- service-model-server.yaml
{%- endif %}
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
{%- if values.rhoaiSelected %}
- rhoai/
{%- endif %}